// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * AutorizacionUsuario generated by hbm2java
 */
public class AutorizacionUsuario implements java.io.Serializable {

	private AutorizacionUsuarioId id;
	private Autorizacion autorizacion;
	private Usuario usuarioByIdUsuario;
	private Usuario usuarioByIdUsuarioUmodif;
	private Date fechaUmodif;

	public AutorizacionUsuario() {
	}

	public AutorizacionUsuario(AutorizacionUsuarioId id, Autorizacion autorizacion, Usuario usuarioByIdUsuario,
			Usuario usuarioByIdUsuarioUmodif, Date fechaUmodif) {
		this.id = id;
		this.autorizacion = autorizacion;
		this.usuarioByIdUsuario = usuarioByIdUsuario;
		this.usuarioByIdUsuarioUmodif = usuarioByIdUsuarioUmodif;
		this.fechaUmodif = fechaUmodif;
	}

	public AutorizacionUsuarioId getId() {
		return this.id;
	}

	public void setId(AutorizacionUsuarioId id) {
		this.id = id;
	}

	public Autorizacion getAutorizacion() {
		return this.autorizacion;
	}

	public void setAutorizacion(Autorizacion autorizacion) {
		this.autorizacion = autorizacion;
	}

	public Usuario getUsuarioByIdUsuario() {
		return this.usuarioByIdUsuario;
	}

	public void setUsuarioByIdUsuario(Usuario usuarioByIdUsuario) {
		this.usuarioByIdUsuario = usuarioByIdUsuario;
	}

	public Usuario getUsuarioByIdUsuarioUmodif() {
		return this.usuarioByIdUsuarioUmodif;
	}

	public void setUsuarioByIdUsuarioUmodif(Usuario usuarioByIdUsuarioUmodif) {
		this.usuarioByIdUsuarioUmodif = usuarioByIdUsuarioUmodif;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

}
