// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Changeset generated by hbm2java
 */
public class Changeset implements java.io.Serializable {

	private Integer idChangeset;
	private String idUsuario;
	private String movement;
	private String idCoro;
	private Date fecha;

	public Changeset() {
	}

	public Changeset(String idUsuario, String movement, String idCoro, Date fecha) {
		this.idUsuario = idUsuario;
		this.movement = movement;
		this.idCoro = idCoro;
		this.fecha = fecha;
	}

	public Integer getIdChangeset() {
		return this.idChangeset;
	}

	public void setIdChangeset(Integer idChangeset) {
		this.idChangeset = idChangeset;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getMovement() {
		return this.movement;
	}

	public void setMovement(String movement) {
		this.movement = movement;
	}

	public String getIdCoro() {
		return this.idCoro;
	}

	public void setIdCoro(String idCoro) {
		this.idCoro = idCoro;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
