// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Choir generated by hbm2java
 */
public class Choir implements java.io.Serializable {

	private int idCoro;
	private String nombre;
	private String autor;
	private Date fechaAct;
	private String descripcion;
	private String numCoro;
	private Integer activo;

	public Choir() {
	}

	public Choir(int idCoro) {
		this.idCoro = idCoro;
	}

	public Choir(int idCoro, String nombre, String autor, Date fechaAct, String descripcion, String numCoro,
			Integer activo) {
		this.idCoro = idCoro;
		this.nombre = nombre;
		this.autor = autor;
		this.fechaAct = fechaAct;
		this.descripcion = descripcion;
		this.numCoro = numCoro;
		this.activo = activo;
	}

	public int getIdCoro() {
		return this.idCoro;
	}

	public void setIdCoro(int idCoro) {
		this.idCoro = idCoro;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	public Date getFechaAct() {
		return this.fechaAct;
	}

	public void setFechaAct(Date fechaAct) {
		this.fechaAct = fechaAct;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getNumCoro() {
		return this.numCoro;
	}

	public void setNumCoro(String numCoro) {
		this.numCoro = numCoro;
	}

	public Integer getActivo() {
		return this.activo;
	}

	public void setActivo(Integer activo) {
		this.activo = activo;
	}

}
