// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * CiudadMunicipio generated by hbm2java
 */
public class CiudadMunicipio implements java.io.Serializable {

	private CiudadMunicipioId id;
	private Ciudad ciudad;

	public CiudadMunicipio() {
	}

	public CiudadMunicipio(CiudadMunicipioId id, Ciudad ciudad) {
		this.id = id;
		this.ciudad = ciudad;
	}

	public CiudadMunicipioId getId() {
		return this.id;
	}

	public void setId(CiudadMunicipioId id) {
		this.id = id;
	}

	public Ciudad getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

}
