// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ColoniaLocalidad generated by hbm2java
 */
public class ColoniaLocalidad implements java.io.Serializable {

	private ColoniaLocalidadId id;
	private DelegacionMunicipio delegacionMunicipio;
	private Usuario usuario;
	private int codigoPostal;
	private int estatus;
	private String nombre;
	private Date fechaUmodif;
	private Set<Direccion> direccions = new HashSet<Direccion>(0);

	public ColoniaLocalidad() {
	}

	public ColoniaLocalidad(ColoniaLocalidadId id, DelegacionMunicipio delegacionMunicipio, Usuario usuario,
			int codigoPostal, int estatus, String nombre, Date fechaUmodif) {
		this.id = id;
		this.delegacionMunicipio = delegacionMunicipio;
		this.usuario = usuario;
		this.codigoPostal = codigoPostal;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
	}

	public ColoniaLocalidad(ColoniaLocalidadId id, DelegacionMunicipio delegacionMunicipio, Usuario usuario,
			int codigoPostal, int estatus, String nombre, Date fechaUmodif, Set<Direccion> direccions) {
		this.id = id;
		this.delegacionMunicipio = delegacionMunicipio;
		this.usuario = usuario;
		this.codigoPostal = codigoPostal;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
		this.direccions = direccions;
	}

	public ColoniaLocalidadId getId() {
		return this.id;
	}

	public void setId(ColoniaLocalidadId id) {
		this.id = id;
	}

	public DelegacionMunicipio getDelegacionMunicipio() {
		return this.delegacionMunicipio;
	}

	public void setDelegacionMunicipio(DelegacionMunicipio delegacionMunicipio) {
		this.delegacionMunicipio = delegacionMunicipio;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(int codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	public Set<Direccion> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions) {
		this.direccions = direccions;
	}

}
