// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DelegacionMunicipio generated by hbm2java
 */
public class DelegacionMunicipio implements java.io.Serializable {

	private DelegacionMunicipioId id;
	private Estado estado;
	private Usuario usuario;
	private String abreviatura;
	private int estatus;
	private String nombre;
	private Date fechaUmodif;
	private Set<ColoniaLocalidad> coloniaLocalidads = new HashSet<ColoniaLocalidad>(0);

	public DelegacionMunicipio() {
	}

	public DelegacionMunicipio(DelegacionMunicipioId id, Estado estado, Usuario usuario, String abreviatura,
			int estatus, String nombre, Date fechaUmodif) {
		this.id = id;
		this.estado = estado;
		this.usuario = usuario;
		this.abreviatura = abreviatura;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
	}

	public DelegacionMunicipio(DelegacionMunicipioId id, Estado estado, Usuario usuario, String abreviatura,
			int estatus, String nombre, Date fechaUmodif, Set<ColoniaLocalidad> coloniaLocalidads) {
		this.id = id;
		this.estado = estado;
		this.usuario = usuario;
		this.abreviatura = abreviatura;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
		this.coloniaLocalidads = coloniaLocalidads;
	}

	public DelegacionMunicipioId getId() {
		return this.id;
	}

	public void setId(DelegacionMunicipioId id) {
		this.id = id;
	}

	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	public Set<ColoniaLocalidad> getColoniaLocalidads() {
		return this.coloniaLocalidads;
	}

	public void setColoniaLocalidads(Set<ColoniaLocalidad> coloniaLocalidads) {
		this.coloniaLocalidads = coloniaLocalidads;
	}

}
