// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Oficina generated by hbm2java
 */
public class Oficina implements java.io.Serializable {

	private Integer id;
	private Direccion direccion;
	private Usuario usuarioByIdUsuarioResponsableOficina;
	private Usuario usuarioByIdUsuarioUmodif;
	private String abreviatura;
	private String clave;
	private int estatus;
	private String nombre;
	private String telefono;
	private Date fechaUmodif;
	private Set<SubOficina> subOficinasForIdOficinaPadre = new HashSet<SubOficina>(0);
	private Set<Perfil> perfils = new HashSet<Perfil>(0);
	private Set<UsuarioOficina> usuarioOficinas = new HashSet<UsuarioOficina>(0);
	private SubOficina subOficinaById;

	public Oficina() {
	}

	public Oficina(Direccion direccion, Usuario usuarioByIdUsuarioUmodif, String clave, int estatus, String nombre,
			Date fechaUmodif) {
		this.direccion = direccion;
		this.usuarioByIdUsuarioUmodif = usuarioByIdUsuarioUmodif;
		this.clave = clave;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
	}

	public Oficina(Direccion direccion, Usuario usuarioByIdUsuarioResponsableOficina, Usuario usuarioByIdUsuarioUmodif,
			String abreviatura, String clave, int estatus, String nombre, String telefono, Date fechaUmodif,
			Set<SubOficina> subOficinasForIdOficinaPadre, Set<Perfil> perfils, Set<UsuarioOficina> usuarioOficinas,
			SubOficina subOficinaById) {
		this.direccion = direccion;
		this.usuarioByIdUsuarioResponsableOficina = usuarioByIdUsuarioResponsableOficina;
		this.usuarioByIdUsuarioUmodif = usuarioByIdUsuarioUmodif;
		this.abreviatura = abreviatura;
		this.clave = clave;
		this.estatus = estatus;
		this.nombre = nombre;
		this.telefono = telefono;
		this.fechaUmodif = fechaUmodif;
		this.subOficinasForIdOficinaPadre = subOficinasForIdOficinaPadre;
		this.perfils = perfils;
		this.usuarioOficinas = usuarioOficinas;
		this.subOficinaById = subOficinaById;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Direccion getDireccion() {
		return this.direccion;
	}

	public void setDireccion(Direccion direccion) {
		this.direccion = direccion;
	}

	public Usuario getUsuarioByIdUsuarioResponsableOficina() {
		return this.usuarioByIdUsuarioResponsableOficina;
	}

	public void setUsuarioByIdUsuarioResponsableOficina(Usuario usuarioByIdUsuarioResponsableOficina) {
		this.usuarioByIdUsuarioResponsableOficina = usuarioByIdUsuarioResponsableOficina;
	}

	public Usuario getUsuarioByIdUsuarioUmodif() {
		return this.usuarioByIdUsuarioUmodif;
	}

	public void setUsuarioByIdUsuarioUmodif(Usuario usuarioByIdUsuarioUmodif) {
		this.usuarioByIdUsuarioUmodif = usuarioByIdUsuarioUmodif;
	}

	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	public Set<SubOficina> getSubOficinasForIdOficinaPadre() {
		return this.subOficinasForIdOficinaPadre;
	}

	public void setSubOficinasForIdOficinaPadre(Set<SubOficina> subOficinasForIdOficinaPadre) {
		this.subOficinasForIdOficinaPadre = subOficinasForIdOficinaPadre;
	}

	public Set<Perfil> getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set<Perfil> perfils) {
		this.perfils = perfils;
	}

	public Set<UsuarioOficina> getUsuarioOficinas() {
		return this.usuarioOficinas;
	}

	public void setUsuarioOficinas(Set<UsuarioOficina> usuarioOficinas) {
		this.usuarioOficinas = usuarioOficinas;
	}

	public SubOficina getSubOficinaById() {
		return this.subOficinaById;
	}

	public void setSubOficinaById(SubOficina subOficinaById) {
		this.subOficinaById = subOficinaById;
	}

}
