// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Publicacion generated by hbm2java
 */
public class Publicacion implements java.io.Serializable {

	private Integer id;
	private Autor autor;
	private Editorial editorial;
	private Tema tema;
	private Usuario usuarioByIdUsuarioUmodif;
	private Usuario usuarioByUsuarioalta;
	private BigDecimal descuento;
	private int estatus;
	private String isbn;
	private String nombre;
	private Short numeroPaginas;
	private byte[] portada;
	private BigDecimal precio;
	private String resumen;
	private String urlArchivo;
	private Date fechaUmodif;

	public Publicacion() {
	}

	public Publicacion(Autor autor, Editorial editorial, Tema tema, Usuario usuarioByIdUsuarioUmodif,
			Usuario usuarioByUsuarioalta, int estatus, String isbn, String nombre, String urlArchivo,
			Date fechaUmodif) {
		this.autor = autor;
		this.editorial = editorial;
		this.tema = tema;
		this.usuarioByIdUsuarioUmodif = usuarioByIdUsuarioUmodif;
		this.usuarioByUsuarioalta = usuarioByUsuarioalta;
		this.estatus = estatus;
		this.isbn = isbn;
		this.nombre = nombre;
		this.urlArchivo = urlArchivo;
		this.fechaUmodif = fechaUmodif;
	}

	public Publicacion(Autor autor, Editorial editorial, Tema tema, Usuario usuarioByIdUsuarioUmodif,
			Usuario usuarioByUsuarioalta, BigDecimal descuento, int estatus, String isbn, String nombre,
			Short numeroPaginas, byte[] portada, BigDecimal precio, String resumen, String urlArchivo,
			Date fechaUmodif) {
		this.autor = autor;
		this.editorial = editorial;
		this.tema = tema;
		this.usuarioByIdUsuarioUmodif = usuarioByIdUsuarioUmodif;
		this.usuarioByUsuarioalta = usuarioByUsuarioalta;
		this.descuento = descuento;
		this.estatus = estatus;
		this.isbn = isbn;
		this.nombre = nombre;
		this.numeroPaginas = numeroPaginas;
		this.portada = portada;
		this.precio = precio;
		this.resumen = resumen;
		this.urlArchivo = urlArchivo;
		this.fechaUmodif = fechaUmodif;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Autor getAutor() {
		return this.autor;
	}

	public void setAutor(Autor autor) {
		this.autor = autor;
	}

	public Editorial getEditorial() {
		return this.editorial;
	}

	public void setEditorial(Editorial editorial) {
		this.editorial = editorial;
	}

	public Tema getTema() {
		return this.tema;
	}

	public void setTema(Tema tema) {
		this.tema = tema;
	}

	public Usuario getUsuarioByIdUsuarioUmodif() {
		return this.usuarioByIdUsuarioUmodif;
	}

	public void setUsuarioByIdUsuarioUmodif(Usuario usuarioByIdUsuarioUmodif) {
		this.usuarioByIdUsuarioUmodif = usuarioByIdUsuarioUmodif;
	}

	public Usuario getUsuarioByUsuarioalta() {
		return this.usuarioByUsuarioalta;
	}

	public void setUsuarioByUsuarioalta(Usuario usuarioByUsuarioalta) {
		this.usuarioByUsuarioalta = usuarioByUsuarioalta;
	}

	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Short getNumeroPaginas() {
		return this.numeroPaginas;
	}

	public void setNumeroPaginas(Short numeroPaginas) {
		this.numeroPaginas = numeroPaginas;
	}

	public byte[] getPortada() {
		return this.portada;
	}

	public void setPortada(byte[] portada) {
		this.portada = portada;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public String getResumen() {
		return this.resumen;
	}

	public void setResumen(String resumen) {
		this.resumen = resumen;
	}

	public String getUrlArchivo() {
		return this.urlArchivo;
	}

	public void setUrlArchivo(String urlArchivo) {
		this.urlArchivo = urlArchivo;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

}
