// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Sistema generated by hbm2java
 */
public class Sistema implements java.io.Serializable {

	private short id;
	private int estatus;
	private String nombre;
	private Set<Autorizacion> autorizacions = new HashSet<Autorizacion>(0);
	private Set<Holliday> hollidays = new HashSet<Holliday>(0);
	private Set<Menu> menus = new HashSet<Menu>(0);

	public Sistema() {
	}

	public Sistema(short id, int estatus, String nombre) {
		this.id = id;
		this.estatus = estatus;
		this.nombre = nombre;
	}

	public Sistema(short id, int estatus, String nombre, Set<Autorizacion> autorizacions, Set<Holliday> hollidays,
			Set<Menu> menus) {
		this.id = id;
		this.estatus = estatus;
		this.nombre = nombre;
		this.autorizacions = autorizacions;
		this.hollidays = hollidays;
		this.menus = menus;
	}

	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Autorizacion> getAutorizacions() {
		return this.autorizacions;
	}

	public void setAutorizacions(Set<Autorizacion> autorizacions) {
		this.autorizacions = autorizacions;
	}

	public Set<Holliday> getHollidays() {
		return this.hollidays;
	}

	public void setHollidays(Set<Holliday> hollidays) {
		this.hollidays = hollidays;
	}

	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

}
