// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * SubMenu generated by hbm2java
 */
public class SubMenu implements java.io.Serializable {

	private short id;
	private Menu menuById;
	private Menu menuByIdMenuPadre;

	public SubMenu() {
	}

	public SubMenu(Menu menuById, Menu menuByIdMenuPadre) {
		this.menuById = menuById;
		this.menuByIdMenuPadre = menuByIdMenuPadre;
	}

	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	public Menu getMenuById() {
		return this.menuById;
	}

	public void setMenuById(Menu menuById) {
		this.menuById = menuById;
	}

	public Menu getMenuByIdMenuPadre() {
		return this.menuByIdMenuPadre;
	}

	public void setMenuByIdMenuPadre(Menu menuByIdMenuPadre) {
		this.menuByIdMenuPadre = menuByIdMenuPadre;
	}

}
