// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * SubOficina generated by hbm2java
 */
public class SubOficina implements java.io.Serializable {

	private int id;
	private Oficina oficinaByIdOficinaPadre;
	private Oficina oficinaById;

	public SubOficina() {
	}

	public SubOficina(Oficina oficinaByIdOficinaPadre, Oficina oficinaById) {
		this.oficinaByIdOficinaPadre = oficinaByIdOficinaPadre;
		this.oficinaById = oficinaById;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Oficina getOficinaByIdOficinaPadre() {
		return this.oficinaByIdOficinaPadre;
	}

	public void setOficinaByIdOficinaPadre(Oficina oficinaByIdOficinaPadre) {
		this.oficinaByIdOficinaPadre = oficinaByIdOficinaPadre;
	}

	public Oficina getOficinaById() {
		return this.oficinaById;
	}

	public void setOficinaById(Oficina oficinaById) {
		this.oficinaById = oficinaById;
	}

}
