// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * UsuarioLector generated by hbm2java
 */
public class UsuarioLector implements java.io.Serializable {

	private int id;
	private Usuario usuario;

	public UsuarioLector() {
	}

	public UsuarioLector(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
