// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * UsuarioMenuId generated by hbm2java
 */
public class UsuarioMenuId implements java.io.Serializable {

	private int idUsuario;
	private short idMenu;

	public UsuarioMenuId() {
	}

	public UsuarioMenuId(int idUsuario, short idMenu) {
		this.idUsuario = idUsuario;
		this.idMenu = idMenu;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public short getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(short idMenu) {
		this.idMenu = idMenu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioMenuId))
			return false;
		UsuarioMenuId castOther = (UsuarioMenuId) other;

		return (this.getIdUsuario() == castOther.getIdUsuario()) && (this.getIdMenu() == castOther.getIdMenu());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdMenu();
		return result;
	}

}
