// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UsuarioInfo generated by hbm2java
 */
public class UsuarioInfo implements java.io.Serializable {

	private int id;
	private Usuario usuarioByIdUsuarioUmodif;
	private Usuario usuarioById;
	private UsuarioPuesto usuarioPuesto;
	private UsuarioTitulo usuarioTitulo;
	private String curp;
	private Date fechaAlta;
	private Date fechaBaja;
	private String rfc;
	private Date fechaUmodif;

	public UsuarioInfo() {
	}

	public UsuarioInfo(Usuario usuarioByIdUsuarioUmodif, Usuario usuarioById, UsuarioPuesto usuarioPuesto,
			Date fechaAlta, Date fechaUmodif) {
		this.usuarioByIdUsuarioUmodif = usuarioByIdUsuarioUmodif;
		this.usuarioById = usuarioById;
		this.usuarioPuesto = usuarioPuesto;
		this.fechaAlta = fechaAlta;
		this.fechaUmodif = fechaUmodif;
	}

	public UsuarioInfo(Usuario usuarioByIdUsuarioUmodif, Usuario usuarioById, UsuarioPuesto usuarioPuesto,
			UsuarioTitulo usuarioTitulo, String curp, Date fechaAlta, Date fechaBaja, String rfc, Date fechaUmodif) {
		this.usuarioByIdUsuarioUmodif = usuarioByIdUsuarioUmodif;
		this.usuarioById = usuarioById;
		this.usuarioPuesto = usuarioPuesto;
		this.usuarioTitulo = usuarioTitulo;
		this.curp = curp;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.rfc = rfc;
		this.fechaUmodif = fechaUmodif;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuarioByIdUsuarioUmodif() {
		return this.usuarioByIdUsuarioUmodif;
	}

	public void setUsuarioByIdUsuarioUmodif(Usuario usuarioByIdUsuarioUmodif) {
		this.usuarioByIdUsuarioUmodif = usuarioByIdUsuarioUmodif;
	}

	public Usuario getUsuarioById() {
		return this.usuarioById;
	}

	public void setUsuarioById(Usuario usuarioById) {
		this.usuarioById = usuarioById;
	}

	public UsuarioPuesto getUsuarioPuesto() {
		return this.usuarioPuesto;
	}

	public void setUsuarioPuesto(UsuarioPuesto usuarioPuesto) {
		this.usuarioPuesto = usuarioPuesto;
	}

	public UsuarioTitulo getUsuarioTitulo() {
		return this.usuarioTitulo;
	}

	public void setUsuarioTitulo(UsuarioTitulo usuarioTitulo) {
		this.usuarioTitulo = usuarioTitulo;
	}

	public String getCurp() {
		return this.curp;
	}

	public void setCurp(String curp) {
		this.curp = curp;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

}
