// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String AMaterno;
	private String APaterno;
	private String email;
	private int estatus;
	private byte[] foto;
	private String login;
	private String nombre;
	private String password;
	private Set<UsuarioOficina> usuarioOficinas = new HashSet<UsuarioOficina>(0);
	private Set<UsuarioPuesto> usuarioPuestos = new HashSet<UsuarioPuesto>(0);
	private Set<Perfil> perfils = new HashSet<Perfil>(0);
	private Set<Holliday> hollidays = new HashSet<Holliday>(0);
	private Set<Pais> paises = new HashSet<Pais>(0);
	private Set<UsuarioInfo> usuarioInfosForIdUsuarioUmodif = new HashSet<UsuarioInfo>(0);
	private Set<Oficina> oficinasForIdUsuarioResponsableOficina = new HashSet<Oficina>(0);
	private Set<UsuarioTitulo> usuarioTitulos = new HashSet<UsuarioTitulo>(0);
	private Set<DelegacionMunicipio> delegacionMunicipios = new HashSet<DelegacionMunicipio>(0);
	private Set<Perfil> perfils_1 = new HashSet<Perfil>(0);
	private Set<Autor> autors = new HashSet<Autor>(0);
	private Set<Editorial> editorials = new HashSet<Editorial>(0);
	private UsuarioLector usuarioLector;
	private Set<SalarioMinimo> salarioMinimos = new HashSet<SalarioMinimo>(0);
	private Set<Estado> estados = new HashSet<Estado>(0);
	private Set<Ciudad> ciudads = new HashSet<Ciudad>(0);
	private Set<Direccion> direccions = new HashSet<Direccion>(0);
	private Set<Publicacion> publicacionsForIdUsuarioUmodif = new HashSet<Publicacion>(0);
	private Set<AutorizacionUsuario> autorizacionUsuariosForIdUsuario = new HashSet<AutorizacionUsuario>(0);
	private Set<Oficina> oficinasForIdUsuarioUmodif = new HashSet<Oficina>(0);
	private UsuarioInfo usuarioInfoById;
	private Set<Tema> temas = new HashSet<Tema>(0);
	private Set<Autorizacion> autorizacions = new HashSet<Autorizacion>(0);
	private Set<UsuarioMenu> usuarioMenus = new HashSet<UsuarioMenu>(0);
	private Set<AutorizacionUsuario> autorizacionUsuariosForIdUsuarioUmodif = new HashSet<AutorizacionUsuario>(0);
	private Set<ColoniaLocalidad> coloniaLocalidads = new HashSet<ColoniaLocalidad>(0);
	private Set<Publicacion> publicacionsForUsuarioalta = new HashSet<Publicacion>(0);

	public Usuario() {
	}

	public Usuario(String APaterno, int estatus, String login, String nombre, String password) {
		this.APaterno = APaterno;
		this.estatus = estatus;
		this.login = login;
		this.nombre = nombre;
		this.password = password;
	}

	public Usuario(String AMaterno, String APaterno, String email, int estatus, byte[] foto, String login,
			String nombre, String password, Set<UsuarioOficina> usuarioOficinas, Set<UsuarioPuesto> usuarioPuestos,
			Set<Perfil> perfils, Set<Holliday> hollidays, Set<Pais> paises,
			Set<UsuarioInfo> usuarioInfosForIdUsuarioUmodif, Set<Oficina> oficinasForIdUsuarioResponsableOficina,
			Set<UsuarioTitulo> usuarioTitulos, Set<DelegacionMunicipio> delegacionMunicipios, Set<Perfil> perfils_1,
			Set<Autor> autors, Set<Editorial> editorials, UsuarioLector usuarioLector,
			Set<SalarioMinimo> salarioMinimos, Set<Estado> estados, Set<Ciudad> ciudads, Set<Direccion> direccions,
			Set<Publicacion> publicacionsForIdUsuarioUmodif, Set<AutorizacionUsuario> autorizacionUsuariosForIdUsuario,
			Set<Oficina> oficinasForIdUsuarioUmodif, UsuarioInfo usuarioInfoById, Set<Tema> temas,
			Set<Autorizacion> autorizacions, Set<UsuarioMenu> usuarioMenus,
			Set<AutorizacionUsuario> autorizacionUsuariosForIdUsuarioUmodif, Set<ColoniaLocalidad> coloniaLocalidads,
			Set<Publicacion> publicacionsForUsuarioalta) {
		this.AMaterno = AMaterno;
		this.APaterno = APaterno;
		this.email = email;
		this.estatus = estatus;
		this.foto = foto;
		this.login = login;
		this.nombre = nombre;
		this.password = password;
		this.usuarioOficinas = usuarioOficinas;
		this.usuarioPuestos = usuarioPuestos;
		this.perfils = perfils;
		this.hollidays = hollidays;
		this.paises = paises;
		this.usuarioInfosForIdUsuarioUmodif = usuarioInfosForIdUsuarioUmodif;
		this.oficinasForIdUsuarioResponsableOficina = oficinasForIdUsuarioResponsableOficina;
		this.usuarioTitulos = usuarioTitulos;
		this.delegacionMunicipios = delegacionMunicipios;
		this.perfils_1 = perfils_1;
		this.autors = autors;
		this.editorials = editorials;
		this.usuarioLector = usuarioLector;
		this.salarioMinimos = salarioMinimos;
		this.estados = estados;
		this.ciudads = ciudads;
		this.direccions = direccions;
		this.publicacionsForIdUsuarioUmodif = publicacionsForIdUsuarioUmodif;
		this.autorizacionUsuariosForIdUsuario = autorizacionUsuariosForIdUsuario;
		this.oficinasForIdUsuarioUmodif = oficinasForIdUsuarioUmodif;
		this.usuarioInfoById = usuarioInfoById;
		this.temas = temas;
		this.autorizacions = autorizacions;
		this.usuarioMenus = usuarioMenus;
		this.autorizacionUsuariosForIdUsuarioUmodif = autorizacionUsuariosForIdUsuarioUmodif;
		this.coloniaLocalidads = coloniaLocalidads;
		this.publicacionsForUsuarioalta = publicacionsForUsuarioalta;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAMaterno() {
		return this.AMaterno;
	}

	public void setAMaterno(String AMaterno) {
		this.AMaterno = AMaterno;
	}

	public String getAPaterno() {
		return this.APaterno;
	}

	public void setAPaterno(String APaterno) {
		this.APaterno = APaterno;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<UsuarioOficina> getUsuarioOficinas() {
		return this.usuarioOficinas;
	}

	public void setUsuarioOficinas(Set<UsuarioOficina> usuarioOficinas) {
		this.usuarioOficinas = usuarioOficinas;
	}

	public Set<UsuarioPuesto> getUsuarioPuestos() {
		return this.usuarioPuestos;
	}

	public void setUsuarioPuestos(Set<UsuarioPuesto> usuarioPuestos) {
		this.usuarioPuestos = usuarioPuestos;
	}

	public Set<Perfil> getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set<Perfil> perfils) {
		this.perfils = perfils;
	}

	public Set<Holliday> getHollidays() {
		return this.hollidays;
	}

	public void setHollidays(Set<Holliday> hollidays) {
		this.hollidays = hollidays;
	}

	public Set<Pais> getPaises() {
		return this.paises;
	}

	public void setPaises(Set<Pais> paises) {
		this.paises = paises;
	}

	public Set<UsuarioInfo> getUsuarioInfosForIdUsuarioUmodif() {
		return this.usuarioInfosForIdUsuarioUmodif;
	}

	public void setUsuarioInfosForIdUsuarioUmodif(Set<UsuarioInfo> usuarioInfosForIdUsuarioUmodif) {
		this.usuarioInfosForIdUsuarioUmodif = usuarioInfosForIdUsuarioUmodif;
	}

	public Set<Oficina> getOficinasForIdUsuarioResponsableOficina() {
		return this.oficinasForIdUsuarioResponsableOficina;
	}

	public void setOficinasForIdUsuarioResponsableOficina(Set<Oficina> oficinasForIdUsuarioResponsableOficina) {
		this.oficinasForIdUsuarioResponsableOficina = oficinasForIdUsuarioResponsableOficina;
	}

	public Set<UsuarioTitulo> getUsuarioTitulos() {
		return this.usuarioTitulos;
	}

	public void setUsuarioTitulos(Set<UsuarioTitulo> usuarioTitulos) {
		this.usuarioTitulos = usuarioTitulos;
	}

	public Set<DelegacionMunicipio> getDelegacionMunicipios() {
		return this.delegacionMunicipios;
	}

	public void setDelegacionMunicipios(Set<DelegacionMunicipio> delegacionMunicipios) {
		this.delegacionMunicipios = delegacionMunicipios;
	}

	public Set<Perfil> getPerfils_1() {
		return this.perfils_1;
	}

	public void setPerfils_1(Set<Perfil> perfils_1) {
		this.perfils_1 = perfils_1;
	}

	public Set<Autor> getAutors() {
		return this.autors;
	}

	public void setAutors(Set<Autor> autors) {
		this.autors = autors;
	}

	public Set<Editorial> getEditorials() {
		return this.editorials;
	}

	public void setEditorials(Set<Editorial> editorials) {
		this.editorials = editorials;
	}

	public UsuarioLector getUsuarioLector() {
		return this.usuarioLector;
	}

	public void setUsuarioLector(UsuarioLector usuarioLector) {
		this.usuarioLector = usuarioLector;
	}

	public Set<SalarioMinimo> getSalarioMinimos() {
		return this.salarioMinimos;
	}

	public void setSalarioMinimos(Set<SalarioMinimo> salarioMinimos) {
		this.salarioMinimos = salarioMinimos;
	}

	public Set<Estado> getEstados() {
		return this.estados;
	}

	public void setEstados(Set<Estado> estados) {
		this.estados = estados;
	}

	public Set<Ciudad> getCiudads() {
		return this.ciudads;
	}

	public void setCiudads(Set<Ciudad> ciudads) {
		this.ciudads = ciudads;
	}

	public Set<Direccion> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions) {
		this.direccions = direccions;
	}

	public Set<Publicacion> getPublicacionsForIdUsuarioUmodif() {
		return this.publicacionsForIdUsuarioUmodif;
	}

	public void setPublicacionsForIdUsuarioUmodif(Set<Publicacion> publicacionsForIdUsuarioUmodif) {
		this.publicacionsForIdUsuarioUmodif = publicacionsForIdUsuarioUmodif;
	}

	public Set<AutorizacionUsuario> getAutorizacionUsuariosForIdUsuario() {
		return this.autorizacionUsuariosForIdUsuario;
	}

	public void setAutorizacionUsuariosForIdUsuario(Set<AutorizacionUsuario> autorizacionUsuariosForIdUsuario) {
		this.autorizacionUsuariosForIdUsuario = autorizacionUsuariosForIdUsuario;
	}

	public Set<Oficina> getOficinasForIdUsuarioUmodif() {
		return this.oficinasForIdUsuarioUmodif;
	}

	public void setOficinasForIdUsuarioUmodif(Set<Oficina> oficinasForIdUsuarioUmodif) {
		this.oficinasForIdUsuarioUmodif = oficinasForIdUsuarioUmodif;
	}

	public UsuarioInfo getUsuarioInfoById() {
		return this.usuarioInfoById;
	}

	public void setUsuarioInfoById(UsuarioInfo usuarioInfoById) {
		this.usuarioInfoById = usuarioInfoById;
	}

	public Set<Tema> getTemas() {
		return this.temas;
	}

	public void setTemas(Set<Tema> temas) {
		this.temas = temas;
	}

	public Set<Autorizacion> getAutorizacions() {
		return this.autorizacions;
	}

	public void setAutorizacions(Set<Autorizacion> autorizacions) {
		this.autorizacions = autorizacions;
	}

	public Set<UsuarioMenu> getUsuarioMenus() {
		return this.usuarioMenus;
	}

	public void setUsuarioMenus(Set<UsuarioMenu> usuarioMenus) {
		this.usuarioMenus = usuarioMenus;
	}

	public Set<AutorizacionUsuario> getAutorizacionUsuariosForIdUsuarioUmodif() {
		return this.autorizacionUsuariosForIdUsuarioUmodif;
	}

	public void setAutorizacionUsuariosForIdUsuarioUmodif(
			Set<AutorizacionUsuario> autorizacionUsuariosForIdUsuarioUmodif) {
		this.autorizacionUsuariosForIdUsuarioUmodif = autorizacionUsuariosForIdUsuarioUmodif;
	}

	public Set<ColoniaLocalidad> getColoniaLocalidads() {
		return this.coloniaLocalidads;
	}

	public void setColoniaLocalidads(Set<ColoniaLocalidad> coloniaLocalidads) {
		this.coloniaLocalidads = coloniaLocalidads;
	}

	public Set<Publicacion> getPublicacionsForUsuarioalta() {
		return this.publicacionsForUsuarioalta;
	}

	public void setPublicacionsForUsuarioalta(Set<Publicacion> publicacionsForUsuarioalta) {
		this.publicacionsForUsuarioalta = publicacionsForUsuarioalta;
	}

}
