// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * UsuarioOficinaId generated by hbm2java
 */
public class UsuarioOficinaId implements java.io.Serializable {

	private int idOficina;
	private int idUsuario;

	public UsuarioOficinaId() {
	}

	public UsuarioOficinaId(int idOficina, int idUsuario) {
		this.idOficina = idOficina;
		this.idUsuario = idUsuario;
	}

	public int getIdOficina() {
		return this.idOficina;
	}

	public void setIdOficina(int idOficina) {
		this.idOficina = idOficina;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioOficinaId))
			return false;
		UsuarioOficinaId castOther = (UsuarioOficinaId) other;

		return (this.getIdOficina() == castOther.getIdOficina()) && (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOficina();
		result = 37 * result + this.getIdUsuario();
		return result;
	}

}
