// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Autor generated by hbm2java
 */
public class Autor implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private String apMaterno;
	private String apPaterno;
	private String email;
	private int estatus;
	private String nombre;
	private String rfc;
	private String telefono;
	private Date fechaUmodif;
	private Set<Publicacion> publicacions = new HashSet<Publicacion>(0);

	public Autor() {
	}

	public Autor(int id, Usuario usuario, String apPaterno, int estatus, String nombre, Date fechaUmodif) {
		this.id = id;
		this.usuario = usuario;
		this.apPaterno = apPaterno;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
	}

	public Autor(int id, Usuario usuario, String apMaterno, String apPaterno, String email, int estatus, String nombre,
			String rfc, String telefono, Date fechaUmodif, Set<Publicacion> publicacions) {
		this.id = id;
		this.usuario = usuario;
		this.apMaterno = apMaterno;
		this.apPaterno = apPaterno;
		this.email = email;
		this.estatus = estatus;
		this.nombre = nombre;
		this.rfc = rfc;
		this.telefono = telefono;
		this.fechaUmodif = fechaUmodif;
		this.publicacions = publicacions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getApMaterno() {
		return this.apMaterno;
	}

	public void setApMaterno(String apMaterno) {
		this.apMaterno = apMaterno;
	}

	public String getApPaterno() {
		return this.apPaterno;
	}

	public void setApPaterno(String apPaterno) {
		this.apPaterno = apPaterno;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	public Set<Publicacion> getPublicacions() {
		return this.publicacions;
	}

	public void setPublicacions(Set<Publicacion> publicacions) {
		this.publicacions = publicacions;
	}

}
