// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * CiudadMunicipioId generated by hbm2java
 */
public class CiudadMunicipioId implements java.io.Serializable {

	private short idCuidad;
	private int idDelegacionMunicipio;
	private short idEstado;

	public CiudadMunicipioId() {
	}

	public CiudadMunicipioId(short idCuidad, int idDelegacionMunicipio, short idEstado) {
		this.idCuidad = idCuidad;
		this.idDelegacionMunicipio = idDelegacionMunicipio;
		this.idEstado = idEstado;
	}

	public short getIdCuidad() {
		return this.idCuidad;
	}

	public void setIdCuidad(short idCuidad) {
		this.idCuidad = idCuidad;
	}

	public int getIdDelegacionMunicipio() {
		return this.idDelegacionMunicipio;
	}

	public void setIdDelegacionMunicipio(int idDelegacionMunicipio) {
		this.idDelegacionMunicipio = idDelegacionMunicipio;
	}

	public short getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(short idEstado) {
		this.idEstado = idEstado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CiudadMunicipioId))
			return false;
		CiudadMunicipioId castOther = (CiudadMunicipioId) other;

		return (this.getIdCuidad() == castOther.getIdCuidad())
				&& (this.getIdDelegacionMunicipio() == castOther.getIdDelegacionMunicipio())
				&& (this.getIdEstado() == castOther.getIdEstado());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCuidad();
		result = 37 * result + this.getIdDelegacionMunicipio();
		result = 37 * result + this.getIdEstado();
		return result;
	}

}
