// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * CiudadId generated by hbm2java
 */
public class CiudadId implements java.io.Serializable {

	private short idEstado;
	private short id;

	public CiudadId() {
	}

	public CiudadId(short idEstado, short id) {
		this.idEstado = idEstado;
		this.id = id;
	}

	public short getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(short idEstado) {
		this.idEstado = idEstado;
	}

	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CiudadId))
			return false;
		CiudadId castOther = (CiudadId) other;

		return (this.getIdEstado() == castOther.getIdEstado()) && (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEstado();
		result = 37 * result + this.getId();
		return result;
	}

}
