package com.bstore.services.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Compra generated by hbm2java
 */
public class Compra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6547708758871807877L;
	private CompraId id;
	private Integer idFormaPago;
	private BigDecimal precioCompra;
	private Date fechaCompra;

	public Compra() {
	}

	public Compra(CompraId id, Date fechaCompra) {
		this.id = id;
		this.fechaCompra = fechaCompra;
	}

	public Compra(CompraId id, Integer idFormaPago, BigDecimal precioCompra, Date fechaCompra) {
		this.id = id;
		this.idFormaPago = idFormaPago;
		this.precioCompra = precioCompra;
		this.fechaCompra = fechaCompra;
	}

	public CompraId getId() {
		return this.id;
	}

	public void setId(CompraId id) {
		this.id = id;
	}

	public Integer getIdFormaPago() {
		return this.idFormaPago;
	}

	public void setIdFormaPago(Integer idFormaPago) {
		this.idFormaPago = idFormaPago;
	}

	public BigDecimal getPrecioCompra() {
		return this.precioCompra;
	}

	public void setPrecioCompra(BigDecimal precioCompra) {
		this.precioCompra = precioCompra;
	}

	public Date getFechaCompra() {
		return this.fechaCompra;
	}

	public void setFechaCompra(Date fechaCompra) {
		this.fechaCompra = fechaCompra;
	}

}
