package com.bstore.services.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Compra generated by hbm2java
 */
public class Compra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6547708758871807877L;
	private CompraId id;
	private FormaPago formaPago;
	private BigDecimal precioCompra;
	private Date fechaCompra;
	
	private String idConekta;
	private String liveMode;
	private String status;
	private String currencyCard;
	private String descriptionCard;
	private String nameCard;
	private String last4Card;
	private String brandCard;
	private String authCodeCard;
	private String amountCard; 
	private String nameUser;
	private String phoneUser;
	private String emailUser;

	public Compra() {
	}

	public Compra(CompraId id, Date fechaCompra) {
		this.id = id;
		this.fechaCompra = fechaCompra;
	}

	public Compra(CompraId id, FormaPago formaPago, BigDecimal precioCompra, Date fechaCompra,
			String idConekta, String livemode, String status, String currencyCard, String descriptionCard,
			String nameCard, String last4Card, String brandCard, String authCodeCard, String amountCard,
			String nameUser, String phoneUser, String emailUser) {
		this.id = id;
		this.formaPago = formaPago;
		this.precioCompra = precioCompra;
		this.fechaCompra = fechaCompra;
		this.idConekta = idConekta;
		this.liveMode = livemode;
		this.status = status;
		this.currencyCard = currencyCard;
		this.descriptionCard = descriptionCard;
		this.nameCard = nameCard;
		this.last4Card = last4Card;
		this.brandCard = brandCard;
		this.authCodeCard = authCodeCard;
		this.amountCard = amountCard;
		this.nameUser = nameUser;
		this.phoneUser = phoneUser;
		this.emailUser = emailUser;	
	}

	public CompraId getId() {
		return this.id;
	}

	public void setId(CompraId id) {
		this.id = id;
	}

	public FormaPago getFormaPago() {
		return formaPago;
	}

	public void setFormaPago(FormaPago formaPago) {
		this.formaPago = formaPago;
	}

	public BigDecimal getPrecioCompra() {
		return this.precioCompra;
	}

	public void setPrecioCompra(BigDecimal precioCompra) {
		this.precioCompra = precioCompra;
	}

	public Date getFechaCompra() {
		return this.fechaCompra;
	}

	public void setFechaCompra(Date fechaCompra) {
		this.fechaCompra = fechaCompra;
	}

	public String getIdConekta() {
		return idConekta;
	}

	public void setIdConekta(String idConekta) {
		this.idConekta = idConekta;
	}

	public String getLiveMode() {
		return liveMode;
	}

	public void setLiveMode(String liveMode) {
		this.liveMode = liveMode;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCurrencyCard() {
		return currencyCard;
	}

	public void setCurrencyCard(String currencyCard) {
		this.currencyCard = currencyCard;
	}

	public String getDescriptionCard() {
		return descriptionCard;
	}

	public void setDescriptionCard(String descriptionCard) {
		this.descriptionCard = descriptionCard;
	}

	public String getNameCard() {
		return nameCard;
	}

	public void setNameCard(String nameCard) {
		this.nameCard = nameCard;
	}

	public String getLast4Card() {
		return last4Card;
	}

	public void setLast4Card(String last4Card) {
		this.last4Card = last4Card;
	}

	public String getBrandCard() {
		return brandCard;
	}

	public void setBrandCard(String brandCard) {
		this.brandCard = brandCard;
	}

	public String getAuthCodeCard() {
		return authCodeCard;
	}

	public void setAuthCodeCard(String authCodeCard) {
		this.authCodeCard = authCodeCard;
	}

	public String getAmountCard() {
		return amountCard;
	}

	public void setAmountCard(String amountCard) {
		this.amountCard = amountCard;
	}

	public String getNameUser() {
		return nameUser;
	}

	public void setNameUser(String nameUser) {
		this.nameUser = nameUser;
	}

	public String getPhoneUser() {
		return phoneUser;
	}

	public void setPhoneUser(String phoneUser) {
		this.phoneUser = phoneUser;
	}

	public String getEmailUser() {
		return emailUser;
	}

	public void setEmailUser(String emailUser) {
		this.emailUser = emailUser;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fechaCompra == null) ? 0 : fechaCompra.hashCode());
		result = prime * result + ((formaPago == null) ? 0 : formaPago.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((precioCompra == null) ? 0 : precioCompra.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Compra other = (Compra) obj;
		if (fechaCompra == null) {
			if (other.fechaCompra != null)
				return false;
		} else if (!fechaCompra.equals(other.fechaCompra))
			return false;
		if (formaPago == null) {
			if (other.formaPago != null)
				return false;
		} else if (!formaPago.equals(other.formaPago))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (precioCompra == null) {
			if (other.precioCompra != null)
				return false;
		} else if (!precioCompra.equals(other.precioCompra))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Compra [id=" + id + ", formaPago=" + formaPago + ", precioCompra=" + precioCompra + ", fechaCompra="
				+ fechaCompra + "]";
	}

}
