package com.bstore.services.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Compra generated by hbm2java
 */
public class Compra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6547708758871807877L;
	private CompraId id;
	private FormaPago formaPago;
	private BigDecimal precioCompra;
	private Date fechaCompra;

	public Compra() {
	}

	public Compra(CompraId id, Date fechaCompra) {
		this.id = id;
		this.fechaCompra = fechaCompra;
	}

	public Compra(CompraId id, FormaPago formaPago, BigDecimal precioCompra, Date fechaCompra) {
		this.id = id;
		this.formaPago = formaPago;
		this.precioCompra = precioCompra;
		this.fechaCompra = fechaCompra;
	}

	public CompraId getId() {
		return this.id;
	}

	public void setId(CompraId id) {
		this.id = id;
	}

	public FormaPago getFormaPago() {
		return formaPago;
	}

	public void setFormaPago(FormaPago formaPago) {
		this.formaPago = formaPago;
	}

	public BigDecimal getPrecioCompra() {
		return this.precioCompra;
	}

	public void setPrecioCompra(BigDecimal precioCompra) {
		this.precioCompra = precioCompra;
	}

	public Date getFechaCompra() {
		return this.fechaCompra;
	}

	public void setFechaCompra(Date fechaCompra) {
		this.fechaCompra = fechaCompra;
	}
	
	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fechaCompra == null) ? 0 : fechaCompra.hashCode());
		result = prime * result + ((formaPago == null) ? 0 : formaPago.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((precioCompra == null) ? 0 : precioCompra.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Compra other = (Compra) obj;
		if (fechaCompra == null) {
			if (other.fechaCompra != null)
				return false;
		} else if (!fechaCompra.equals(other.fechaCompra))
			return false;
		if (formaPago == null) {
			if (other.formaPago != null)
				return false;
		} else if (!formaPago.equals(other.formaPago))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (precioCompra == null) {
			if (other.precioCompra != null)
				return false;
		} else if (!precioCompra.equals(other.precioCompra))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Compra [id=" + id + ", formaPago=" + formaPago + ", precioCompra=" + precioCompra + ", fechaCompra="
				+ fechaCompra + "]";
	}

}
