// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Deliveryfailed generated by hbm2java
 */
public class Deliveryfailed implements java.io.Serializable {

	private Integer idFailed;
	private String mailTo;
	private String mailFrom;
	private String subject;
	private String name;
	private String body;
	private String typeFailed;
	private Date dateSend;

	public Deliveryfailed() {
	}

	public Deliveryfailed(String mailTo, String mailFrom, String subject, String name, String body, String typeFailed,
			Date dateSend) {
		this.mailTo = mailTo;
		this.mailFrom = mailFrom;
		this.subject = subject;
		this.name = name;
		this.body = body;
		this.typeFailed = typeFailed;
		this.dateSend = dateSend;
	}

	public Integer getIdFailed() {
		return this.idFailed;
	}

	public void setIdFailed(Integer idFailed) {
		this.idFailed = idFailed;
	}

	public String getMailTo() {
		return this.mailTo;
	}

	public void setMailTo(String mailTo) {
		this.mailTo = mailTo;
	}

	public String getMailFrom() {
		return this.mailFrom;
	}

	public void setMailFrom(String mailFrom) {
		this.mailFrom = mailFrom;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public String getTypeFailed() {
		return this.typeFailed;
	}

	public void setTypeFailed(String typeFailed) {
		this.typeFailed = typeFailed;
	}

	public Date getDateSend() {
		return this.dateSend;
	}

	public void setDateSend(Date dateSend) {
		this.dateSend = dateSend;
	}

}
