// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Direccion generated by hbm2java
 */
public class Direccion implements java.io.Serializable {

	private Long id;
	private ColoniaLocalidad coloniaLocalidad;
	private Usuario usuario;
	private String calle;
	private int codigoPostal;
	private Date fechaAlta;
	private String numeroExt;
	private String numeroInt;
	private String referencia;
	private Date fechaUmodif;
	private Set<Oficina> oficinas = new HashSet<Oficina>(0);
	private Set<Editorial> editorials = new HashSet<Editorial>(0);

	public Direccion() {
	}

	public Direccion(ColoniaLocalidad coloniaLocalidad, Usuario usuario, String calle, int codigoPostal, Date fechaAlta,
			String numeroExt, Date fechaUmodif) {
		this.coloniaLocalidad = coloniaLocalidad;
		this.usuario = usuario;
		this.calle = calle;
		this.codigoPostal = codigoPostal;
		this.fechaAlta = fechaAlta;
		this.numeroExt = numeroExt;
		this.fechaUmodif = fechaUmodif;
	}

	public Direccion(ColoniaLocalidad coloniaLocalidad, Usuario usuario, String calle, int codigoPostal, Date fechaAlta,
			String numeroExt, String numeroInt, String referencia, Date fechaUmodif, Set<Oficina> oficinas,
			Set<Editorial> editorials) {
		this.coloniaLocalidad = coloniaLocalidad;
		this.usuario = usuario;
		this.calle = calle;
		this.codigoPostal = codigoPostal;
		this.fechaAlta = fechaAlta;
		this.numeroExt = numeroExt;
		this.numeroInt = numeroInt;
		this.referencia = referencia;
		this.fechaUmodif = fechaUmodif;
		this.oficinas = oficinas;
		this.editorials = editorials;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public ColoniaLocalidad getColoniaLocalidad() {
		return this.coloniaLocalidad;
	}

	public void setColoniaLocalidad(ColoniaLocalidad coloniaLocalidad) {
		this.coloniaLocalidad = coloniaLocalidad;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public int getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(int codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public String getNumeroExt() {
		return this.numeroExt;
	}

	public void setNumeroExt(String numeroExt) {
		this.numeroExt = numeroExt;
	}

	public String getNumeroInt() {
		return this.numeroInt;
	}

	public void setNumeroInt(String numeroInt) {
		this.numeroInt = numeroInt;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	public Set<Oficina> getOficinas() {
		return this.oficinas;
	}

	public void setOficinas(Set<Oficina> oficinas) {
		this.oficinas = oficinas;
	}

	public Set<Editorial> getEditorials() {
		return this.editorials;
	}

	public void setEditorials(Set<Editorial> editorials) {
		this.editorials = editorials;
	}

}
