// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado implements java.io.Serializable {

	private short id;
	private Pais pais;
	private Usuario usuario;
	private int estatus;
	private String nombre;
	private Date fechaUmodif;
	private Set<Ciudad> ciudads = new HashSet<Ciudad>(0);
	private Set<DelegacionMunicipio> delegacionMunicipios = new HashSet<DelegacionMunicipio>(0);

	public Estado() {
	}

	public Estado(short id, Pais pais, Usuario usuario, int estatus, String nombre, Date fechaUmodif) {
		this.id = id;
		this.pais = pais;
		this.usuario = usuario;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
	}

	public Estado(short id, Pais pais, Usuario usuario, int estatus, String nombre, Date fechaUmodif,
			Set<Ciudad> ciudads, Set<DelegacionMunicipio> delegacionMunicipios) {
		this.id = id;
		this.pais = pais;
		this.usuario = usuario;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
		this.ciudads = ciudads;
		this.delegacionMunicipios = delegacionMunicipios;
	}

	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	public Set<Ciudad> getCiudads() {
		return this.ciudads;
	}

	public void setCiudads(Set<Ciudad> ciudads) {
		this.ciudads = ciudads;
	}

	public Set<DelegacionMunicipio> getDelegacionMunicipios() {
		return this.delegacionMunicipios;
	}

	public void setDelegacionMunicipios(Set<DelegacionMunicipio> delegacionMunicipios) {
		this.delegacionMunicipios = delegacionMunicipios;
	}

}
