// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	private short id;
	private Usuario usuario;
	private String abreviatura2;
	private String abreviatura3;
	private int estatus;
	private String nombre;
	private Date fechaUmodif;
	private Set<Estado> estados = new HashSet<Estado>(0);

	public Pais() {
	}

	public Pais(short id, Usuario usuario, int estatus, String nombre, Date fechaUmodif) {
		this.id = id;
		this.usuario = usuario;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
	}

	public Pais(short id, Usuario usuario, String abreviatura2, String abreviatura3, int estatus, String nombre,
			Date fechaUmodif, Set<Estado> estados) {
		this.id = id;
		this.usuario = usuario;
		this.abreviatura2 = abreviatura2;
		this.abreviatura3 = abreviatura3;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
		this.estados = estados;
	}

	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getAbreviatura2() {
		return this.abreviatura2;
	}

	public void setAbreviatura2(String abreviatura2) {
		this.abreviatura2 = abreviatura2;
	}

	public String getAbreviatura3() {
		return this.abreviatura3;
	}

	public void setAbreviatura3(String abreviatura3) {
		this.abreviatura3 = abreviatura3;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	public Set<Estado> getEstados() {
		return this.estados;
	}

	public void setEstados(Set<Estado> estados) {
		this.estados = estados;
	}

}
