package com.bstore.services.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

/**
 * PerfilColeccionId generated by hbm2java
 */
public class PerfilColeccionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6353159629539706601L;
	private int idPerfil;
	private int coleccionId;

	public PerfilColeccionId() {
	}

	public PerfilColeccionId(int idPerfil, int coleccionId) {
		this.idPerfil = idPerfil;
		this.coleccionId = coleccionId;
	}

	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	public int getColeccionId() {
		return this.coleccionId;
	}

	public void setColeccionId(int coleccionId) {
		this.coleccionId = coleccionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfilColeccionId))
			return false;
		PerfilColeccionId castOther = (PerfilColeccionId) other;

		return (this.getIdPerfil() == castOther.getIdPerfil()) && (this.getColeccionId() == castOther.getColeccionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPerfil();
		result = 37 * result + this.getColeccionId();
		return result;
	}

}
