package com.bstore.services.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

/**
 * PerfilColeccion generated by hbm2java
 */
public class PerfilColeccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2864430329025086814L;
	private PerfilColeccionId id;

	public PerfilColeccion() {
	}

	public PerfilColeccion(PerfilColeccionId id) {
		this.id = id;
	}

	public PerfilColeccionId getId() {
		return this.id;
	}

	public void setId(PerfilColeccionId id) {
		this.id = id;
	}

}
