// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * Property generated by hbm2java
 */
public class Property implements java.io.Serializable {

	private int id;
	private String llave;
	private String value;
	private Integer active;

	public Property() {
	}

	public Property(int id) {
		this.id = id;
	}

	public Property(int id, String llave, String value, Integer active) {
		this.id = id;
		this.llave = llave;
		this.value = value;
		this.active = active;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLlave() {
		return this.llave;
	}

	public void setLlave(String llave) {
		this.llave = llave;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

}
