package com.bstore.services.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

/**
 * PublicacionId generated by hbm2java
 */
public class PublicacionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8481177492133453944L;
	private int id;
	private int fuenteId;
	private int coleccionId;

	public PublicacionId() {
	}

	public PublicacionId(int id, int fuenteId, int coleccionId) {
		this.id = id;
		this.fuenteId = fuenteId;
		this.coleccionId = coleccionId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getFuenteId() {
		return this.fuenteId;
	}

	public void setFuenteId(int fuenteId) {
		this.fuenteId = fuenteId;
	}

	public int getColeccionId() {
		return this.coleccionId;
	}

	public void setColeccionId(int coleccionId) {
		this.coleccionId = coleccionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PublicacionId))
			return false;
		PublicacionId castOther = (PublicacionId) other;

		return (this.getId() == castOther.getId()) && (this.getFuenteId() == castOther.getFuenteId())
				&& (this.getColeccionId() == castOther.getColeccionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getFuenteId();
		result = 37 * result + this.getColeccionId();
		return result;
	}

}
