// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SalarioMinimo generated by hbm2java
 */
public class SalarioMinimo implements java.io.Serializable {

	private Short id;
	private long version;
	private Usuario usuario;
	private BigDecimal cantidad;
	private int estatus;
	private Date fechaAplicacion;
	private Date fechaUmodif;

	public SalarioMinimo() {
	}

	public SalarioMinimo(Usuario usuario, BigDecimal cantidad, int estatus, Date fechaAplicacion, Date fechaUmodif) {
		this.usuario = usuario;
		this.cantidad = cantidad;
		this.estatus = estatus;
		this.fechaAplicacion = fechaAplicacion;
		this.fechaUmodif = fechaUmodif;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public Date getFechaAplicacion() {
		return this.fechaAplicacion;
	}

	public void setFechaAplicacion(Date fechaAplicacion) {
		this.fechaAplicacion = fechaAplicacion;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

}
