// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * Subtema generated by hbm2java
 */
public class Subtema implements java.io.Serializable {

	private int id;
	private Tema tema;
	private String nombre;

	public Subtema() {
	}

	public Subtema(int id, Tema tema, String nombre) {
		this.id = id;
		this.tema = tema;
		this.nombre = nombre;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Tema getTema() {
		return this.tema;
	}

	public void setTema(Tema tema) {
		this.tema = tema;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
