// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private int estatus;
	private String nombre;
	private Date fechaUmodif;
	private Set<Subtema> subtemas = new HashSet<Subtema>(0);
	private Set<Publicacion> publicacions = new HashSet<Publicacion>(0);

	public Tema() {
	}

	public Tema(int id, Usuario usuario, int estatus, String nombre, Date fechaUmodif) {
		this.id = id;
		this.usuario = usuario;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
	}

	public Tema(int id, Usuario usuario, int estatus, String nombre, Date fechaUmodif, Set<Subtema> subtemas,
			Set<Publicacion> publicacions) {
		this.id = id;
		this.usuario = usuario;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
		this.subtemas = subtemas;
		this.publicacions = publicacions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	public Set<Subtema> getSubtemas() {
		return this.subtemas;
	}

	public void setSubtemas(Set<Subtema> subtemas) {
		this.subtemas = subtemas;
	}

	public Set<Publicacion> getPublicacions() {
		return this.publicacions;
	}

	public void setPublicacions(Set<Publicacion> publicacions) {
		this.publicacions = publicacions;
	}

}
