// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int idUsuario;
	private String nombre;
	private char sexo;
	private Date fechaAlta;
	private Date ultConexion;
	private String notificaciones;
	private String email;
	private String password;
	private Date nacimiento;
	private String actividad;

	public User() {
	}

	public User(int idUsuario, String nombre, char sexo, Date fechaAlta, Date ultConexion, String email,
			String password) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
		this.sexo = sexo;
		this.fechaAlta = fechaAlta;
		this.ultConexion = ultConexion;
		this.email = email;
		this.password = password;
	}

	public User(int idUsuario, String nombre, char sexo, Date fechaAlta, Date ultConexion, String notificaciones,
			String email, String password, Date nacimiento, String actividad) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
		this.sexo = sexo;
		this.fechaAlta = fechaAlta;
		this.ultConexion = ultConexion;
		this.notificaciones = notificaciones;
		this.email = email;
		this.password = password;
		this.nacimiento = nacimiento;
		this.actividad = actividad;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public char getSexo() {
		return this.sexo;
	}

	public void setSexo(char sexo) {
		this.sexo = sexo;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getUltConexion() {
		return this.ultConexion;
	}

	public void setUltConexion(Date ultConexion) {
		this.ultConexion = ultConexion;
	}

	public String getNotificaciones() {
		return this.notificaciones;
	}

	public void setNotificaciones(String notificaciones) {
		this.notificaciones = notificaciones;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getNacimiento() {
		return this.nacimiento;
	}

	public void setNacimiento(Date nacimiento) {
		this.nacimiento = nacimiento;
	}

	public String getActividad() {
		return this.actividad;
	}

	public void setActividad(String actividad) {
		this.actividad = actividad;
	}

}
