// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * UsuarioLectorPublicacionId generated by hbm2java
 */
public class UsuarioLectorPublicacionId implements java.io.Serializable {

	private int idUsuarioLector;
	private int idPublicacion;

	public UsuarioLectorPublicacionId() {
	}

	public UsuarioLectorPublicacionId(int idUsuarioLector, int idPublicacion) {
		this.idUsuarioLector = idUsuarioLector;
		this.idPublicacion = idPublicacion;
	}

	public int getIdUsuarioLector() {
		return this.idUsuarioLector;
	}

	public void setIdUsuarioLector(int idUsuarioLector) {
		this.idUsuarioLector = idUsuarioLector;
	}

	public int getIdPublicacion() {
		return this.idPublicacion;
	}

	public void setIdPublicacion(int idPublicacion) {
		this.idPublicacion = idPublicacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioLectorPublicacionId))
			return false;
		UsuarioLectorPublicacionId castOther = (UsuarioLectorPublicacionId) other;

		return (this.getIdUsuarioLector() == castOther.getIdUsuarioLector())
				&& (this.getIdPublicacion() == castOther.getIdPublicacion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuarioLector();
		result = 37 * result + this.getIdPublicacion();
		return result;
	}

}
