// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * UsuarioOficina generated by hbm2java
 */
public class UsuarioOficina implements java.io.Serializable {

	private UsuarioOficinaId id;
	private Oficina oficina;
	private Usuario usuario;
	private int estatus;

	public UsuarioOficina() {
	}

	public UsuarioOficina(UsuarioOficinaId id, Oficina oficina, Usuario usuario, int estatus) {
		this.id = id;
		this.oficina = oficina;
		this.usuario = usuario;
		this.estatus = estatus;
	}

	public UsuarioOficinaId getId() {
		return this.id;
	}

	public void setId(UsuarioOficinaId id) {
		this.id = id;
	}

	public Oficina getOficina() {
		return this.oficina;
	}

	public void setOficina(Oficina oficina) {
		this.oficina = oficina;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

}
