package com.bstore.services.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioId generated by hbm2java
 */
public class UsuarioId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7103104690659393684L;
	private int id;
	private int compraIdUsuario;
	private int compraIdPublicacion;

	public UsuarioId() {
	}

	public UsuarioId(int id, int compraIdUsuario, int compraIdPublicacion) {
		this.id = id;
		this.compraIdUsuario = compraIdUsuario;
		this.compraIdPublicacion = compraIdPublicacion;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getCompraIdUsuario() {
		return this.compraIdUsuario;
	}

	public void setCompraIdUsuario(int compraIdUsuario) {
		this.compraIdUsuario = compraIdUsuario;
	}

	public int getCompraIdPublicacion() {
		return this.compraIdPublicacion;
	}

	public void setCompraIdPublicacion(int compraIdPublicacion) {
		this.compraIdPublicacion = compraIdPublicacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioId))
			return false;
		UsuarioId castOther = (UsuarioId) other;

		return (this.getId() == castOther.getId()) && (this.getCompraIdUsuario() == castOther.getCompraIdUsuario())
				&& (this.getCompraIdPublicacion() == castOther.getCompraIdPublicacion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getCompraIdUsuario();
		result = 37 * result + this.getCompraIdPublicacion();
		return result;
	}

}
