// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

/**
 * UsuarioMenu generated by hbm2java
 */
public class UsuarioMenu implements java.io.Serializable {

	private UsuarioMenuId id;
	private Menu menu;
	private Usuario usuario;
	private int estatus;

	public UsuarioMenu() {
	}

	public UsuarioMenu(UsuarioMenuId id, Menu menu, Usuario usuario, int estatus) {
		this.id = id;
		this.menu = menu;
		this.usuario = usuario;
		this.estatus = estatus;
	}

	public UsuarioMenuId getId() {
		return this.id;
	}

	public void setId(UsuarioMenuId id) {
		this.id = id;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

}
