// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UsuarioLectorPublicacion generated by hbm2java
 */
public class UsuarioLectorPublicacion implements java.io.Serializable {

	private UsuarioLectorPublicacionId id;
	private Date fechaCompra;

	public UsuarioLectorPublicacion() {
	}

	public UsuarioLectorPublicacion(UsuarioLectorPublicacionId id, Date fechaCompra) {
		this.id = id;
		this.fechaCompra = fechaCompra;
	}

	public UsuarioLectorPublicacionId getId() {
		return this.id;
	}

	public void setId(UsuarioLectorPublicacionId id) {
		this.id = id;
	}

	public Date getFechaCompra() {
		return this.fechaCompra;
	}

	public void setFechaCompra(Date fechaCompra) {
		this.fechaCompra = fechaCompra;
	}

}
