// default package
// Generated 31-may-2016 0:05:40 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioTitulo generated by hbm2java
 */
public class UsuarioTitulo implements java.io.Serializable {

	private Short id;
	private Usuario usuario;
	private String abreviatura;
	private int estatus;
	private String nombre;
	private Date fechaUmodif;
	private Set<UsuarioInfo> usuarioInfos = new HashSet<UsuarioInfo>(0);

	public UsuarioTitulo() {
	}

	public UsuarioTitulo(Usuario usuario, String abreviatura, int estatus, String nombre, Date fechaUmodif) {
		this.usuario = usuario;
		this.abreviatura = abreviatura;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
	}

	public UsuarioTitulo(Usuario usuario, String abreviatura, int estatus, String nombre, Date fechaUmodif,
			Set<UsuarioInfo> usuarioInfos) {
		this.usuario = usuario;
		this.abreviatura = abreviatura;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
		this.usuarioInfos = usuarioInfos;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	public Set<UsuarioInfo> getUsuarioInfos() {
		return this.usuarioInfos;
	}

	public void setUsuarioInfos(Set<UsuarioInfo> usuarioInfos) {
		this.usuarioInfos = usuarioInfos;
	}

}
